### ISSUE TITLE
Exit(1) ValueError: 'auto' is not in file

### ISSUE THREAD

**Issue by utookmyid** [clinton-hall/nzbToMedia#1055] opened 2016-06-07 10:58 UTC
having all kinds of issues, subj being the latest.  Storms this past wk/power outages, killed my Transmission-QT, now while it appears to complet a NZB d/l, I get the ValueError.  Guessing it has something to do with transmission, but don't where to start.  Pls help. 
[nzbtomedia.log.txt](https://github.com/clinton-hall/nzbToMedia/files/302378/nzbtomedia.log.txt)

**Comment by clinton-hall** [comment] 2016-06-07 13:04
There is a LOT of development in Nightly right now.

Please try again and let us know if the problem is resolved with recent updates, or otherwise switch back to master branch and verify if all works ok (this will rule out Transmission as the cause)

**Comment by labrys** [comment] 2016-06-07 13:40
@clinton-hall this is likely caused by another place that the config will need to be type-cast to dict as it's failing with a ValueError.  It appears like it's failing during an attempt at getting the fork configuration (the 'auto' value) and may be fixed by #1057.

**Comment by utookmyid** [comment] 2016-06-08 12:24
FWIW:  went back to master, nzbs run to completion, THANK YOU.  Transmission, however, doesn't even show a settings.json; torrents stuck at magnetized transfer *sigh*

**Comment by clinton-hall** [comment] 2016-06-08 13:02
transmission might not show the settings.json... but it must be on the system somewhere.
Via ssh/terminal try `find / -name "settings.json"`
you would need to run this as root, or su, or with `sudo` in front...

**Comment by utookmyid** [comment] 2016-06-08 15:00
I have a Pi/Linux, but this is about my Win 10 box.  Rest of the story ... I also lost my SlickVPN connectivity about the same time Transmission/CouchPotato ran into these probs.  Browsing one of yr other posts, maybe VPN is the source of all my probs?

**Comment by clinton-hall** [comment] 2016-06-10 11:09
Win10... with Transmission?
I must not have kept up to date. I didn't realise there was a good windows port for transmsission...

**Comment by utookmyid** [comment] 2016-06-10 11:26
1. I fixed my VPN (selected a diff port).  In turn, my CP/Transmission now work :) 2.  I found a transmission-2.92-x64.msi which works fine with win 10.

**Comment by clinton-hall** [comment] 2016-06-12 23:53
Good to know Transmission works on Win10. To be honest I don't have a lot to do with torrents or Windows these days (although I will admit I think Win10 has been a big improvement on Win8!!)

**Comment by clinton-hall** [comment] 2016-06-12 23:53
So all working well for you again?

**Comment by utookmyid** [comment] 2016-06-13 02:32
yup, all that panic came down to changing the port on VPN; SB/SR/CP/Tx all good now :) FWIW, I'd rather go Pi, but still trying to grab Linux, PC in the short term.

**Comment by clinton-hall** [comment] 2016-06-13 07:26
Glad to hear. Yell put if you have any more issues.

**Closed by clinton-hall** 2016-06-13 07:26 UTC
