### ISSUE TITLE
Error Code 128

### ISSUE THREAD

**Issue by phybersplice** [clinton-hall/nzbToMedia#1963] opened 2023-03-02 04:59 UTC
**Describe the bug**
Migrated from nzbget (depricated) to sabnzbd (linuxserver.io).

**Technical Specs**
1. Running on Synology 1821+ (Docker)
2. Python version 3.10.10
3. Download Client SABnbzd
4. Intended Media Management (Radarr, Sonarr) '....'

**Expected behavior**
I haven't seen these errors before.

**Log**
`fatal: detected dubious ownership in repository at '/config/scripts/nzbToMedia'
To add an exception for this directory, call:

git config --global --add safe.directory /config/scripts/nzbToMedia
fatal: detected dubious ownership in repository at '/config/scripts/nzbToMedia'
To add an exception for this directory, call:

git config --global --add safe.directory /config/scripts/nzbToMedia
/config/scripts/nzbToMedia/libs/common/beets/mediafile.py:19: UserWarning: beets.mediafile is deprecated; use mediafile instead
warnings.warn("beets.mediafile is deprecated; use mediafile instead")
[23:49:59] [INFO]::MAIN: Loading config from [/config/scripts/nzbToMedia/autoProcessMedia.cfg]
[23:49:59] [INFO]::MAIN: Python v3.10 will reach end of life in 1310 days.
[23:49:59] [INFO]::MAIN: Checking database structure...
[23:49:59] [INFO]::MAIN: Version checking is disabled, not checking for the newest version
[23:49:59] [INFO]::MAIN: nzbToMedia Version:12.1.11 Branch:master (Linux 4.4.180+)
[23:49:59] [INFO]::MAIN: #########################################################
[23:49:59] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
[23:49:59] [INFO]::MAIN: #########################################################
[23:49:59] [INFO]::MAIN: Script triggered from SABnzbd 3.7.2.
[23:49:59] [INFO]::MAIN: Auto-detected SECTION:Radarr
[23:49:59] [INFO]::MAIN: Calling Radarr:movies to post-process:Maybe.I.Do.2023.720p.AMZN.WEB-DL.DDP5.1.H.264-FLUX
[23:49:59] [INFO]::MAIN: Attemping imdbID lookup for Maybe.I.Do.2023.720p.AMZN.WEB-DL.DDP5.1.H.264-FLUX
[23:49:59] [INFO]::MAIN: Searching folder and file names for imdbID ...
[23:49:59] [INFO]::MAIN: Searching IMDB for imdbID ...
[23:49:59] [INFO]::MAIN: Found imdbID [tt20879602]
[23:49:59] [POSTPROCESS]::RADARR: Starting DownloadedMoviesScan scan for Maybe.I.Do.2023.720p.AMZN.WEB-DL.DDP5.1.H.264-FLUX
[23:49:59] [POSTPROCESS]::RADARR: Checking for status change, please stand by ...
[23:50:59] [POSTPROCESS]::RADARR: Checking for status change, please stand by ...
[23:50:59] [INFO]::MAIN: The /config/scripts/nzbToMedia/nzbToMedia.py script completed successfully.
Changing to directory: /config/scripts/nzbToMedia

-- Cleaning bytecode --
WARNING: Automatic cleanup could not be executed.
If errors occur, manual cleanup may be required.
REASON : Error Code: 128

-- Cleaning folders: ['libs', 'core'] --
WARNING: Automatic cleanup could not be executed.
If errors occur, manual cleanup may be required.
REASON : Error Code: 128
Returning to directory:  /app/sabnzbd

-- Cleanup finished --

Radarr: Successfully post-processed Maybe.I.Do.2023.720p.AMZN.WEB-DL.DDP5.1.H.264-FLUX!

root@9c9fb9667027:/config/scripts# ls -ltr
total 0
drwxr-xr-x 1 abc abc 930 Mar  1 23:50 nzbToMedia

oot@9c9fb9667027:/config/scripts/nzbToMedia# ls -ltr
total 284
-rwxr-xr-x 1 abc abc  6390 Mar  1 23:19 cleanup.py
-rwxr-xr-x 1 abc abc  1695 Mar  1 23:19 azure-pipelines.yml
-rwxr-xr-x 1 abc abc 25595 Mar  1 23:19 autoProcessMedia.cfg.spec
-rwxr-xr-x 1 abc abc    26 Mar  1 23:19 _config.yml
-rwxr-xr-x 1 abc abc 16974 Mar  1 23:19 TorrentToMedia.py
-rwxr-xr-x 1 abc abc   517 Mar  1 23:19 getffmpeg.sh
-rwxr-xr-x 1 abc abc  5507 Mar  1 23:19 eol.py
drwxr-xr-x 1 abc abc   352 Mar  1 23:19 core
drwxr-xr-x 1 abc abc   320 Mar  1 23:19 libs
-rwxr-xr-x 1 abc abc  3824 Mar  1 23:19 nzbToHeadPhones.py
-rwxr-xr-x 1 abc abc  2993 Mar  1 23:19 nzbToGamez.py
-rwxr-xr-x 1 abc abc  7699 Mar  1 23:19 nzbToCouchPotato.py
-rwxr-xr-x 1 abc abc 35127 Mar  1 23:19 license.txt
-rwxr-xr-x 1 abc abc  7469 Mar  1 23:19 nzbToRadarr.py
-rwxr-xr-x 1 abc abc  7369 Mar  1 23:19 nzbToNzbDrone.py
-rwxr-xr-x 1 abc abc  3378 Mar  1 23:19 nzbToMylar.py
-rwxr-xr-x 1 abc abc 19604 Mar  1 23:19 nzbToMedia.py
-rwxr-xr-x 1 abc abc  6979 Mar  1 23:19 nzbToLidarr.py
-rwxr-xr-x 1 abc abc  3413 Mar  1 23:19 nzbToLazyLibrarian.py
-rwxr-xr-x 1 abc abc  3838 Mar  1 23:19 setup.py
-rwxr-xr-x 1 abc abc  7462 Mar  1 23:19 nzbToWatcher3.py
-rwxr-xr-x 1 abc abc  7580 Mar  1 23:19 nzbToSickBeard.py
-rwxr-xr-x 1 abc abc  7581 Mar  1 23:19 nzbToSiCKRAGE.py
-rwxr-xr-x 1 abc abc  4023 Mar  1 23:19 tox.ini
drwxr-xr-x 1 abc abc   110 Mar  1 23:19 tests
drwxr-xr-x 1 abc abc    84 Mar  1 23:23 __pycache__
drwxr-xr-x 1 abc abc    28 Mar  1 23:24 logs
-rwxr-xr-x 1 abc abc 27506 Mar  1 23:49 autoProcessMedia.cfg.old
-rwxr-xr-x 1 abc abc 27506 Mar  1 23:49 autoProcessMedia.cfg
-rwxr-xr-x 1 abc abc 16384 Mar  1 23:50 nzbtomedia.db
 `

**Comment by clinton-hall** [comment] 2023-03-02 06:59
if you moved from NZBGet to SABnzbd is this the same nzbToMedia setup?
Do NZBGet and SABnzbd run as different users? if so, that could explain most of the issues.

I would recommend doing a chown -R to the nzbToMedia directory to set the ownership tot he user that runs SABnzbd.

**Comment by phybersplice** [comment] 2023-03-02 07:13
> 



> if you moved from NZBGet to SABnzbd is this the same nzbToMedia setup? Do NZBGet and SABnzbd run as different users? if so, that could explain most of the issues.
> 
> I would recommend doing a chown -R to the nzbToMedia directory to set the ownership tot he user that runs SABnzbd.

The docker container is new, but I was able to copy over the autoProcessMedia.cfg from nzbget to sabnzbd.
I spun up the old docker-nzbget container (haven't deleted it yet) to compare permissions/ownership of the nzbToMedia folder and they seem to be the same as docker-sabnzbd.
I used this [guide](https://drfrankenstein.co.uk/step-2-setting-up-a-restricted-docker-user-and-obtaining-ids/) to create a user that's limited to docker.
The docker .yaml is set to launch the container and run as uid 1028 / gid 100 which is the dockerlimited user as per the guide.  

When I go into the console of the container I get this:
root@50aad48a40e7:/# id
uid=0(root) gid=0(root) groups=0(root),1(bin),2(daemon),3(sys),4(adm),6(disk),10(wheel),11(floppy),20(dialout),26(tape),27(video)

**Comment by phybersplice** [comment] 2023-03-02 09:50
I might talk it over with "Dr. Frankenstein" - the author of the guides.  I've got him on my Discord.  Will get back to you.

**Comment by clinton-hall** [comment] 2023-03-02 09:59
ok... so the user is abc... and that is the owner of nzbToMedia.
So I can't see why that is detecting a dubious ownership.

the other thing to try is
`git config --global --add safe.directory /config/scripts/nzbToMedia`
this should ignore those warnings and keep doing the git check. Hopefully this also completes the git cleanup.

**Comment by clinton-hall** [comment] 2023-03-02 10:02
Perhaps if this was cloned as root, the ownership hasn't been set for the .git directory?
what is the ownership of /config/scripts/nzbToMedia/.git

perhaps try `chown -R abc:abc /config/scripts/nzbToMedia/.git`

**Comment by phybersplice** [comment] 2023-03-02 10:29
I did chown -R abc:abc /config/scripts/nzbToMedia

Here's the output now:

`/app/sabnzbd/scripts/nzbToMedia/libs/common/beets/mediafile.py:19: UserWarning: beets.mediafile is deprecated; use mediafile instead
warnings.warn("beets.mediafile is deprecated; use mediafile instead")
[05:09:05] [INFO]::MAIN: Loading config from [/app/sabnzbd/scripts/nzbToMedia/autoProcessMedia.cfg]
[05:09:05] [INFO]::MAIN: Python v3.10 will reach end of life in 1309 days.
[05:09:05] [INFO]::MAIN: Checking database structure...
[05:09:05] [INFO]::MAIN: Database upgrade required: Initial Schema
[05:09:05] [INFO]::MAIN: Version checking is disabled, not checking for the newest version
[05:09:05] [INFO]::MAIN: nzbToMedia Version:12.1.11 Branch:master (Linux 4.4.180+)
[05:09:05] [INFO]::MAIN: #########################################################
[05:09:05] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
[05:09:05] [INFO]::MAIN: #########################################################
[05:09:05] [INFO]::MAIN: Script triggered from SABnzbd 3.7.2.
[05:09:05] [INFO]::MAIN: Auto-detected SECTION:Radarr
[05:09:05] [INFO]::MAIN: Calling Radarr:movies to post-process:M3gan.2022.UNRATED.720p.WEB.h264-SKYFiRE
[05:09:05] [INFO]::MAIN: Attemping imdbID lookup for M3gan.2022.UNRATED.720p.WEB.h264-SKYFiRE
[05:09:05] [INFO]::MAIN: Searching folder and file names for imdbID ...
[05:09:05] [INFO]::MAIN: Searching IMDB for imdbID ...
[05:09:06] [INFO]::MAIN: Found imdbID [tt8760708]
[05:09:06] [POSTPROCESS]::RADARR: Starting DownloadedMoviesScan scan for M3gan.2022.UNRATED.720p.WEB.h264-SKYFiRE
[05:09:06] [POSTPROCESS]::RADARR: Checking for status change, please stand by ...
[05:10:06] [POSTPROCESS]::RADARR: Checking for status change, please stand by ...
[05:10:06] [INFO]::MAIN: The /app/sabnzbd/scripts/nzbToMedia/nzbToMedia.py script completed successfully.
Changing to directory: /app/sabnzbd/scripts/nzbToMedia

-- Cleaning bytecode --
b'Removing __pycache__/\n'
b'Removing __pycache__/\n'

-- Cleaning folders: ['libs', 'core'] --
No folders to clean

Returning to directory:  /app/sabnzbd

-- Cleanup finished --

Radarr: Successfully post-processed M3gan.2022.UNRATED.720p.WEB.h264-SKYFiRE!`

**Comment by phybersplice** [comment] 2023-03-03 06:47
@clinton-hall  is the above log output a "successful" one?

**Comment by clinton-hall** [comment] 2023-03-06 07:28
it looks successful from what I can see. I note that it did not check git version.
In autoProcessMedia.cfg it looks like you must have
```
[General]
    version_notify = 0
```

to check and update you would need to set
```
[General]
    version_notify = 1
```

**Comment by phybersplice** [comment] 2023-03-08 03:01
@clinton-hall I updated the .cfg file and it is now checking for updates.

However, I am intrigued by what this is:
/app/sabnzbd/scripts/nzbToMedia/libs/common/beets/mediafile.py:19: UserWarning: beets.mediafile is deprecated; use mediafile instead
warnings.warn("beets.mediafile is deprecated; use mediafile instead")

Future update coming?

**Comment by clinton-hall** [comment] 2023-03-08 08:38
yeah potentially: https://github.com/clinton-hall/nzbToMedia/pull/1959
the issue is we can't move to mediafile until python2.7 is dropped.

**Comment by MattPark** [comment] 2024-03-02 17:37
Recommend closing this unless you want more informative log messaging.  I had the same error, only 1 file, .git/index was owned by root for some reason. `sudo chown user.group -R .git/` solved for me.

**Closed** 2024-03-03 07:43 UTC
