### ISSUE TITLE
TorrentToMedia.py from Transmission to Sickgear fail

### ISSUE THREAD

**Issue by warbringer** [clinton-hall/nzbToMedia#1838] opened 2021-08-06 13:32 UTC
**Describe the bug**
When transmission attempts to have Sickgear post-process a downloaded TV show, it fails.

**Technical Specs**
Running Sickgear, Transmission and nzbtomedia on a QNAP T856-Pro. All applications have been installed via Sherpa and Python version is 3.9.5
Download clients available are nzbget and transmission. This issue pertains to Transmission version 3.00.
Media management system is Sickgear (BRANCH: master @ py3.9.5 / COMMIT: 7770062 @ 0.24.15). Previously used SickChill which didn't have this problem.

**Expected behavior**
The expectation is that Sickgear finds a suitable torrent for a TV show, sends it to transmission and that transmission sends it back to sickgear for postprocessing when completed.

**Log**
In sickgear, the following settings are enable/disable in Media Process:
![afbeelding](https://user-images.githubusercontent.com/3033052/128517809-a0796208-c0b9-49e6-bf09-5915f16dc799.png)

```
2021-08-06 10:11:16 INFO    ::MAIN: Loading config from [/share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia/autoProcessMedia.cfg]
2021-08-06 10:11:16 INFO    ::MAIN: Python v3.9 will reach end of life in 1521 days.
2021-08-06 10:11:16 INFO    ::MAIN: Checking database structure...
2021-08-06 10:11:16 INFO    ::MAIN: Checking if git needs an update
2021-08-06 10:11:17 INFO    ::MAIN: No update needed
2021-08-06 10:11:17 INFO    ::MAIN: nzbToMedia Version:f9dde62762f7ad4fa6a5bfca892af7263a28a3e3 Branch:master (Linux 3.4.6)
2021-08-06 10:11:17 WARNING ::MAIN: Failed to locate ffprobe. Video corruption detection disabled!
2021-08-06 10:11:17 WARNING ::MAIN: Install ffmpeg with x264 support to enable this feature  ...
2021-08-06 10:11:18 INFO    ::MAIN: #########################################################
2021-08-06 10:11:18 INFO    ::MAIN: ## ..::[TorrentToMedia.py]::.. ##
2021-08-06 10:11:18 INFO    ::MAIN: #########################################################
2021-08-06 10:11:18 INFO    ::MAIN: SEARCH: Found torrent directory Star.Wars.The.Bad.Batch.S01E15.1080p.WEB.H264-EMPATHY[rarbg] in input directory directory /share/Download/torrents/complete/tv
2021-08-06 10:11:18 INFO    ::MAIN: SEARCH: Setting input_directory to /share/Download/torrents/complete/tv/Star.Wars.The.Bad.Batch.S01E15.1080p.WEB.H264-EMPATHY[rarbg]
2021-08-06 10:11:18 INFO    ::MAIN: Auto-detected SECTION:SickBeard
2021-08-06 10:11:23 INFO    ::MAIN: Output directory set to: /share/Download/torrents/processed/tv/Star.Wars.The.Bad.Batch.S01E15.1080p.WEB.H264-EMPATHY[rarbg]
2021-08-06 10:11:23 INFO    ::COPYLINK: MEDIAFILE: [Star.Wars.The.Bad.Batch.S01E15.1080p.WEB.H264-EMPATHY.mkv]
2021-08-06 10:11:24 INFO    ::COPYLINK: SOURCE FOLDER: [/share/Download/torrents/complete/tv/Star.Wars.The.Bad.Batch.S01E15.1080p.WEB.H264-EMPATHY[rarbg]]
2021-08-06 10:11:24 INFO    ::COPYLINK: TARGET FOLDER: [/share/Download/torrents/processed/tv/Star.Wars.The.Bad.Batch.S01E15.1080p.WEB.H264-EMPATHY[rarbg]]
2021-08-06 10:11:24 INFO    ::COPYLINK: Moving SOURCE MEDIAFILE -> TARGET FOLDER
2021-08-06 10:11:24 INFO    ::COPYLINK: MEDIAFILE: [star.wars.the.bad.batch.s01e15.1080p.web.h264-empathy.nfo]
2021-08-06 10:11:24 INFO    ::COPYLINK: SOURCE FOLDER: [/share/Download/torrents/complete/tv/Star.Wars.The.Bad.Batch.S01E15.1080p.WEB.H264-EMPATHY[rarbg]]
2021-08-06 10:11:24 INFO    ::COPYLINK: TARGET FOLDER: [/share/Download/torrents/processed/tv/Star.Wars.The.Bad.Batch.S01E15.1080p.WEB.H264-EMPATHY[rarbg]]
2021-08-06 10:11:24 INFO    ::COPYLINK: Moving SOURCE MEDIAFILE -> TARGET FOLDER
2021-08-06 10:11:24 INFO    ::MAIN: FLATTEN: Flattening directory: /share/Download/torrents/processed/tv/Star.Wars.The.Bad.Batch.S01E15.1080p.WEB.H264-EMPATHY[rarbg]
2021-08-06 10:11:24 INFO    ::MAIN: Found 1 media files in /share/Download/torrents/processed/tv/Star.Wars.The.Bad.Batch.S01E15.1080p.WEB.H264-EMPATHY[rarbg]
2021-08-06 10:11:24 INFO    ::MAIN: Calling SickBeard:tv to post-process:Star.Wars.The.Bad.Batch.S01E15.1080p.WEB.H264-EMPATHY[rarbg]
2021-08-06 10:11:28 INFO    ::MAIN: Attempting to auto-detect tv fork
2021-08-06 10:11:29 INFO    ::MAIN: SickBeard:tv fork auto-detection found custom params {'path': None, 'type': None, 'force_replace': None, 'failed': None, 'return_data': None, 'is_priority': None, 'process_method': None, 'cmd': 'sg.postprocess'}
2021-08-06 10:11:29 INFO    ::MAIN: SickBeard:tv fork set to failed-torrent
2021-08-06 10:11:29 INFO    ::MAIN: SickBeard:tv Could not create a fork object for failed-torrent. Probaly class not added yet.
2021-08-06 10:11:29 POSTPROCESS::SICKBEARD: SUCCESS: The download succeeded, sending a post-process request
2021-08-06 10:11:29 ERROR   ::MAIN: A problem was reported in the autoProcess* script. If torrent was paused we will resume seeding
2021-08-06 10:11:34 ERROR   ::MAIN: A problem was reported in the /share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia/TorrentToMedia.py script.
```

This is the relevant max debug level log from Sickgear
```
2021-08-06 10:11:28 DEBUG    TORNADO :: API (nzbToMedia):: 127.0.0.1 - gave correct API KEY: nzbToMedia. ACCESS GRANTED
2021-08-06 10:11:28 DEBUG    API^WEB_0 :: API (nzbToMedia):: cmd: 'sg.postprocess'
2021-08-06 10:11:29 DEBUG    API^WEB_0 :: API (nzbToMedia):: all args: '()'
2021-08-06 10:11:29 DEBUG    API^WEB_0 :: API (nzbToMedia):: all kwargs: '{'help': '1'}'
2021-08-06 10:11:29 DEBUG    API^WEB_0 :: API (nzbToMedia):: sg.postprocess: curKwargs {'help': '1'}
2021-08-06 10:11:29 DEBUG    TORNADO :: API (nzbToMedia):: 127.0.0.1 - gave correct API KEY: nzbToMedia. ACCESS GRANTED
2021-08-06 10:11:29 DEBUG    API^WEB_0 :: API (nzbToMedia):: cmd: 'postprocess'
2021-08-06 10:11:29 DEBUG    API^WEB_0 :: API (nzbToMedia):: all args: '()'
2021-08-06 10:11:29 DEBUG    API^WEB_0 :: API (nzbToMedia):: all kwargs: '{'dir': '/share/Download/torrents/processed/tv/Star.Wars.The.Bad.Batch.S01E15.1080p.WEB.H264-EMPATHY[rarbg]', 'failed': '0', 'quiet': '1', 'nzbName': 'Star.Wars.The.Bad.Batch.S01E15.1080p.WEB.H264-EMPATHY[rarbg]'}'
2021-08-06 10:11:29 DEBUG    API^WEB_0 :: API (nzbToMedia):: postprocess: curKwargs {'dir': '/share/Download/torrents/processed/tv/Star.Wars.The.Bad.Batch.S01E15.1080p.WEB.H264-EMPATHY[rarbg]', 'failed': '0', 'quiet': '1', 'nzbName': 'Star.Wars.The.Bad.Batch.S01E15.1080p.WEB.H264-EMPATHY[rarbg]'}
2021-08-06 10:11:29 WARNING  API^WEB_0 :: API (nzbToMedia):: SickBeard API call "postprocess" should be replaced with SickGear API "sg.postprocess" calls to get much improved detail and functionality, contact your App developer and ask them to update their code.
```

**Comment by clinton-hall** [comment] 2021-08-08 22:54
Are you able to switch to `fork-patch-1` branch and test?
I believe the issue is with the detected fork not being passed correctly for "custom" forks (i.e. when any combination of parameters is different to the known list).

**Comment by warbringer** [comment] 2021-08-09 15:14
I tried setting sickbeard-detection to sickgear specifically but that gave the same error. I switched to the fork-patch-1 which gave the below result.

```
# git checkout fork-patch-1
Switched to branch 'fork-patch-1'
Your branch is up to date with 'origin/fork-patch-1'.
# /opt/bin/python3.9 ./TorrentToMedia.py

-- Cleaning bytecode --
b'Removing __pycache__/\n'
b'Removing __pycache__/\n'

-- Cleaning folders: ['libs', 'core'] --
No folders to clean


-- Cleanup finished --

Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/nzbToMedia/./TorrentToMedia.py", line 22, in <module>
    from core.auto_process import comics, games, movies, music, tv, books
  File "/share/CACHEDEV1_DATA/.qpkg/nzbToMedia/core/auto_process/tv.py", line 27, in <module>
    from core.auto_process.managers.sickbeard import InitSickBeard
  File "/share/CACHEDEV1_DATA/.qpkg/nzbToMedia/core/auto_process/managers/sickbeard.py", line 172
    (section=self.section, category=self.input_category, self.fork[0]))
                                                                     ^
SyntaxError: positional argument follows keyword argument
```

Looked at it and you probably meant 

```(section=self.section, category=self.input_category, fork=fork[0]))``` on line 172.

Reran it and the log then gives:
```
[17:09:15] [INFO]::MAIN: Attempting to auto-detect tv fork
[17:09:15] [DEBUG]::MAIN: Removing excess parameters: ['delete', 'delete_files', 'delete_on', 'dir', 'dirName', 'force', 'force_next', 'ignore_subs', 'is priority', 'proc_dir', 'resource']
[17:09:15] [INFO]::MAIN: SickBeard:tv fork auto-detection found custom params {'failed': None, 'type': None, 'cmd': 'sg.postprocess', 'path': None, 'return_data': None, 'process_method': None, 'is_priority': None, 'force_replace': None}
[17:09:15] [INFO]::MAIN: SickBeard:tv fork set to a
[17:09:15] [DEBUG]::MAIN: Create object for fork custom
[17:09:15] [INFO]::MAIN: SickBeard:tv Could not create a fork object for custom. Probaly class not added yet.
[17:09:15] [POSTPROCESS]::SICKBEARD: SUCCESS: The download succeeded, sending a post-process request
[17:09:15] [DEBUG]::SICKBEARD: Opening URL: http://localhost:7181/api/15715c037a407ed2cdf6fe327e8976e9/ with params: {'failed': 0, 'cmd': 'sg.postprocess', 'path': '/share/Download/torrents/processed/tv/Rick.and.Morty.S05E05.1080p.WEBRip.x264-CAKES[rarbg]', 'return_data': 0, 'nzbName': 'Rick.and.Morty.S05E05.1080p.WEBRip.x264-CAKES[rarbg]'}
[17:09:19] [DB]::DB: Updating DB download status of Rick.and.Morty.S05E05.1080p.WEBRip.x264-CAKES[rarbg] to 1
[17:09:19] [DB]::MAIN: nzbtomedia.db: UPDATE downloads SET status=?, last_update=? WHERE input_name=? with args [1, 738011, 'Rick.and.Morty.S05E05.1080p.WEBRip.x264-CAKES[rarbg]']
[17:09:19] [DEBUG]::MAIN: Deleting torrent Rick.and.Morty.S05E05.1080p.WEBRip.x264-CAKES[rarbg] from transmission
[17:09:24] [INFO]::CLEANDIR: Directory /share/Download/torrents/processed/tv/Rick.and.Morty.S05E05.1080p.WEBRip.x264-CAKES[rarbg] has been processed and removed ...
[17:09:24] [INFO]::MAIN: The ./TorrentToMedia.py script completed successfully.
```

The torrent is post-processed as expected! 😄

**Comment by clinton-hall** [comment] 2021-08-09 20:20
Thanks... 
originally 
`(section=self.section, category=self.input_category, fork=fork[0]))`
but with the changes I made It should have been
`(section=self.section, category=self.input_category, fork=self.fork[0]))`
I made a mistake yesterday and dropped the `fork=`

This only impacts the logging. so doesn't really change the way anything is detected. Unfortunately this logging error caused the script to fail.

The only difference between the change you made, and what I have just made is:
Your change will log `SickBeard:tv fork set to a`  (Note that `a` is the first letter of `auto` which it the config defined fork)
My chnage will now log `SickBeard:tv fork set to custom` (`custom` is the detected fork).

I have updated this now in `fork-patch-1` branch.

**Comment by clinton-hall** [comment] 2021-08-09 21:06
I have also just added a fix to esnure SickGear fork actually matches and gets detected correctly.

So should now log: `SickBeard:tv fork set to SickGear-api`

**Comment by warbringer** [comment] 2021-08-10 09:16
```
2021-08-10 11:15:14 INFO    ::MAIN: SickBeard:tv fork auto-detection successful ...
2021-08-10 11:15:14 INFO    ::MAIN: SickBeard:tv fork set to SickGear-api
```

Post-processing works now and Sickgear is being recognized via fork auto-detection. This one can be merged and closed 👍

**Comment by clinton-hall** [comment] 2021-08-10 09:32
Merged into nightly branch.

**Closed** 2024-04-26 01:31 UTC
