### ISSUE TITLE
Having a hash symbol in sickchill password is causing post processing to fail.

### ISSUE THREAD

**Issue by captainhowie** [clinton-hall/nzbToMedia#1765] opened 2020-08-13 08:04 UTC
Hi There
I have recently upgraded to Python3 and am using sabnzbd and sickchill on a QNAP NAS. I was having some trouble setting up the post processing and have discovered that the issue is with the fact that my password has a # at the end of it and this often is removed from the autoProcessMedia.cfg file after saving and running it.

Is there a restriction on the use of the # symbol in passwords for the purposes of the .cfg script and if not, is there some sort of parenthesis required to indicate that it is part of the password and not a comment.

Thanks
Andrew

**Comment by clinton-hall** [comment] 2020-08-13 09:46
yeah a `#` is a "comment out character in python.... so `password = test12#34` will be handled as `test12`
I just did a test, and if I put in quotes `password = "test12#34"` this handled the password as `test12#34`... I haven't tested as far as testing this trough the request.post (url posting)....

Also, I recommend setting up the sickchill api and using that, not the user/pass. This works better for auto-fork as well.

**Comment by captainhowie** [comment] 2020-08-13 09:49
Thanks.  I was advised to leave the API blank as there is a recent issue causing a crash during post processing - is this now resolved?

**Comment by clinton-hall** [comment] 2020-08-13 09:53
ok, who advised? I was not aware of this issue (certainly I have not experienced it).
Try the password in quotes as above, and hopefully the api issue is resolved soon.

**Comment by captainhowie** [comment] 2020-08-13 10:02
Sorry - I hope I'm not getting anyone in trouble here - OneCD said it was a very recent issue so leave it blank temporarily.

https://forum.qnap.com/viewtopic.php?f=320&t=132373&start=1815

**Comment by clinton-hall** [comment] 2020-08-13 10:30
nah... not getting anyone in trouble at all... it's good when we can all share our findings/isues and try to get everything playing nice.

looks like OneCD was suggesting that the api interface causes a crash in SABnzbd postprocessing.
As I use NZBGet that may explain why I haven't seen it...

@OneCDOnly
Do you have any insights into this issue? Is there anything that I need to try and fix here or is this something to be addressed within SickChill or SABnzbd and if so has it been reported?

**Comment by captainhowie** [comment] 2020-08-13 10:36
Thanks so much for being really prompt and responsive.  Appreciate your help.  Good luck with the API issue (if it is actually your issue to begin with!)

**Comment by OneCDOnly** [comment] 2020-08-13 19:30
> @OneCDOnly
> Do you have any insights into this issue (about not using SickChill api in autoProcessMedia.cfg as this causes a SABnzbd crash)? Is there anything that I need to try and fix here or is this something to be addressed within SickChill or SABnzbd and if so has it been reported?

@clinton-hall sorry, I don't know a lot about this. It only happens when running the new SickChill (rewritten for Python 3), so it may be a SickChill error. @miigotu is hard-at-work re-tooling SickChill to work correctly in Python 3.

The error appears in the SABnznd -> nzbToMedia logs as a crash. @niwa2 posted about this problem and their solution [here](https://forum.qnap.com/viewtopic.php?p=761275#p761275). 

Frankly, I didn't know [where](https://forum.qnap.com/viewtopic.php?p=761350#p761350) this issue should be reported.

**Comment by OneCDOnly** [comment] 2020-08-13 23:27
```
[22:49:02] [INFO]::MAIN: Attempting to auto-detect tv fork
[22:49:02] [ERROR]::MAIN: Failed to get data from JSON
```
Just had a thought: can nzbToMedia detect SickChill?

**Comment by clinton-hall** [comment] 2020-08-14 00:27
Ah, I hadn't realised this was referencing the Py3 SickChill branch.

I believe this has been raised already #1759

It does appear that (at that time) SickChill was not able to parse json data due to byte vs string issues (and I think everyone who has ported something from py2 to py3 has encountered this).

So currently nzbToMedia cannot detect SickChill (py3) using autofork.

I'll see if I have time this weekend (heck, we may be back in lockdown) to try and set up SickChill Py3 and do some testing.
I still have a QNAP box, so if I use sherpa I should be able to set up this combination?

**Comment by OneCDOnly** [comment] 2020-08-14 00:46
> So currently nzbToMedia cannot detect SickChill (py3) using autofork.

It would be great to have autofork working but if not, is it possible to prevent this problem by setting a manual fork? 

> I still have a QNAP box, so if I use sherpa I should be able to set up this combination?

Yes, that should work fine. But, I get the same effect on my Debian 10.5 server running SickChill (develop). So, it's not really a QNAP issue. :wink:

**Comment by clinton-hall** [comment] 2020-08-14 00:57
Sorry, Realised it wasn't a QNAp issue, but I have the following options

1. Asustor Nas (currently running SickChill for my use using py2... so I don't want to break this just yet)
2. QNAP Nas (Currently not running anydownlaod Apps
3. Trying to remember how to log into my Azure VM

So I figured QNAP would be the easiest way to go.

**Comment by OneCDOnly** [comment] 2020-08-14 00:58
>     2. QNAP Nas (Currently not running anydownlaod Apps

BTW: what is the firmware version on your QNAP?

**Comment by miigotu** [comment] 2020-08-14 01:43
@clinton-hall `python3 -m pip install sickchil`l will get you a working py3 version

If someone can get me a traceback I can fix whatever it is.

**Comment by clinton-hall** [comment] 2020-08-14 09:06
@miigotu 
```
AA sickchill.views.api.webapi.ApiError: param: 'subject' with given value: 'b'postprocess'' is out of allowed range '['help', 'future', 'episode', 'episode.search', 'episode.setstatus', 'episode.subtitlesearch', 'exceptions', 'history', 'history.clear', 'history.trim', 'failed', 'backlog', 'logs', 'logs.clear', 'sb', 'postprocess', 'sb.addrootdir', 'sb.checkversion', 'sb.checkscheduler', 'sb.deleterootdir', 'sb.getdefaults', 'sb.getmessages', 'sb.getrootdirs', 'sb.pausebacklog', 'sb.ping', 'sb.restart', 'sb.dailysearch', 'sb.propersearch', 'sb.subtitlesearch', 'sb.searchindexers', 'sb.searchtvdb', 'sb.searchtvrage', 'sb.setdefaults', 'sb.update', 'sb.shutdown', 'show', 'show.addexisting', 'show.addnew', 'show.cache', 'show.delete', 'show.getquality', 'show.getposter', 'show.getbanner', 'show.getnetworklogo', 'show.getfanart', 'show.pause', 'show.refresh', 'show.seasonlist', 'show.seasons', 'show.setquality', 'show.stats', 'show.update', 'shows', 'shows.stats']'
AA raise ApiError("param: '" + str(name) + "' with given value: '" + str(
AA File "C:\Users\fock_\AppData\Local\Programs\Python\Python38\lib\site-packages\sickchill\views\api\webapi.py", line 405, in _check_param_value
AA self._check_param_value(default, key, allowed_values)
AA File "C:\Users\fock_\AppData\Local\Programs\Python\Python38\lib\site-packages\sickchill\views\api\webapi.py", line 335, in check_params
AA self.subject, args = self.check_params(args, kwargs, "subject", "help", False, "string", list(function_mapper))
AA File "C:\Users\fock_\AppData\Local\Programs\Python\Python38\lib\site-packages\sickchill\views\api\webapi.py", line 637, in __init__
AA to_call = func(cur_args, cur_kwargs)
AA File "C:\Users\fock_\AppData\Local\Programs\Python\Python38\lib\site-packages\sickchill\views\api\webapi.py", line 164, in call_dispatcher
2020-08-14 20:54:39 INFO :: WEBSERVER :: Traceback (most recent call last):
```
so it looks like the incoming api call `http://xx.xx.xx.xx:8081/api/xxxxxxxxxxxxxxxx/?cmd=help&subject=postprocess` is having the param interpreted/imported as a byte code, not string and therefore not matching any available commands.

I pasted the url into the browser to test and get the same error logged in the browser
```
{"data": {}, "message": "param: 'subject' with given value: 'b'postprocess'' is out of allowed range '['help', 'future', 'episode', 'episode.search', 'episode.setstatus', 'episode.subtitlesearch', 'exceptions', 'history', 'history.clear', 'history.trim', 'failed', 'backlog', 'logs', 'logs.clear', 'sb', 'postprocess', 'sb.addrootdir', 'sb.checkversion', 'sb.checkscheduler', 'sb.deleterootdir', 'sb.getdefaults', 'sb.getmessages', 'sb.getrootdirs', 'sb.pausebacklog', 'sb.ping', 'sb.restart', 'sb.dailysearch', 'sb.propersearch', 'sb.subtitlesearch', 'sb.searchindexers', 'sb.searchtvdb', 'sb.searchtvrage', 'sb.setdefaults', 'sb.update', 'sb.shutdown', 'show', 'show.addexisting', 'show.addnew', 'show.cache', 'show.delete', 'show.getquality', 'show.getposter', 'show.getbanner', 'show.getnetworklogo', 'show.getfanart', 'show.pause', 'show.refresh', 'show.seasonlist', 'show.seasons', 'show.setquality', 'show.stats', 'show.update', 'shows', 'shows.stats']'", "result": "error"}
```

**Comment by miigotu** [comment] 2020-08-14 09:33
I can cast that to the right type, but I'm confused why it works with a blank fork set?

**Comment by clinton-hall** [comment] 2020-08-15 00:42
@miigotu 

When you specify a fork in nzbToMedia, we just pass in all of the parameters that are defined for that fork. So we skip this step (autofork) where we actually hit the postprocess help page to get a list of possible parameters.

Then, when we actually call the postprocess command we pass all the params as a dictionary through the requests session... so it is possible that params are being correctly detected when passed as a dict, but when passed directly through the url these are causing issues.

Potentially, at this end, I could pass `?cmd=help&subject=postprocess` as a dict `params ={'cmd': 'help', 'subject': 'postprocess'}`,
and see if that works... and this would be cleaner....

However I would have expected to be able to hit the help page via url locally anyway, so possibly worth investigating that.

**Comment by miigotu** [comment] 2020-08-15 00:50
Yeah when I responded earlier I thought that was the postprocess command (which works).

I will check the help command shortly.

**Comment by miigotu** [comment] 2020-08-15 01:29
https://github.com/SickChill/SickChill/pull/6642/files#diff-1df4fcb78e368befe86dba988029d4a7R65

**Comment by miigotu** [comment] 2020-08-15 01:41
Also, yes a dict as params will work. I could expose it for post if you want also, but for now it's only GET

**Comment by clinton-hall** [comment] 2020-08-15 07:31
I just added the params as dict to nightly.... Can't say for sure if that really did much... but between that, and having updated SickChill to latest, the auto-fork worked.
```
[19:28:14] [DEBUG]::SERVER: Server responded at http://10.1.1.35:8081
[19:28:14] [INFO]::MAIN: Attempting to auto-detect tv fork
[19:28:14] [DEBUG]::MAIN: Removing excess parameters: ['delete_files', 'delete_on', 'dir', 'dirName', 'force', 'ignore_subs', 'is priority', 'proc_dir']
[19:28:14] [INFO]::MAIN: SickBeard:tv fork auto-detection successful ...
[19:28:14] [INFO]::MAIN: SickBeard:tv fork set to SickChill-api
```
@captainhowie 
If you update SickChill and switch nzbToMedia to nightly branch, you should be able to set the apikey in autoProcessMedia.cfg and it should work correctly.

**Comment by clinton-hall** [comment] 2020-08-21 01:56
For what it is worth... I have switched my Asustor NAS over to running SickChill develop and everything appears to be working (in terms of hand-shaking between Apps).

@miigotu I have submitted this SickChill App to Asustor App Center. It currently does a git clone and if 'SickChill.py' doesn't exist it checks out the develop branch before launching. 
So in theory, once this is merged to master it will just keep users on master (default) branch. Also, since it now requires the Python3 App (not Python) it won't allow a user to upgrade without installing Python3 App first.

Behind the scenes it use venv to install all requirements into a separate environment to prevent contamination with other Apps.

**Comment by OneCDOnly** [comment] 2020-08-21 02:06
> Behind the scenes it use venv to install all requirements into a separate environment to prevent contamination with other Apps.

I'm just looking at doing the same thing with the sherpa apps. 🤓

**Comment by miigotu** [comment] 2020-08-21 02:23
> For what it is worth... I have switched my Asustor NAS over to running SickChill develop and everything appears to be working (in terms of hand-shaking between Apps).
> 
> @miigotu I have submitted this SickChill App to Asustor App Center. It currently does a git clone and if 'SickChill.py' doesn't exist it checks out the develop branch before launching. 
> So in theory, once this is merged to master it will just keep users on master (default) branch. Also, since it now requires the Python3 App (not Python) it won't allow a user to upgrade without installing Python3 App first.
> 
> Behind the scenes it use venv to install all requirements into a separate environment to prevent contamination with other Apps.

It is available on pypi now, and python3 comes with pip. I'm working on a pip updater in the app. Pip will be a better way than git because of git not tracking folders and people will get compiled requirements specifically for their device. I currently patch sys.path if it is not installed in site-packages or user-site, but we really want to avoid the bundled libs if possible.

**Comment by OneCDOnly** [comment] 2020-08-21 02:45
> It is available on pypi now, and python3 comes with pip. I'm working on a pip updater in the app. Pip will be a better way than git because of git not tracking folders and people will get compiled requirements specifically for their device. I currently patch sys.path if it is not installed in site-packages or user-site, but we really want to avoid the bundled libs if possible.

Wow, I just tried the pip install. Had a working SickChill in under 30 seconds! Good work @miigotu 👍🏽

**Comment by clinton-hall** [comment] 2020-08-21 02:47
I'll have a play and see if I can package it to install via pip (as I already do for the requirements).
I was going to do this originally, but decided git was safer as I could test for the existence of SickChill.py.... but now I realise that this was flawed thinking... pip in python 3 will only install the python 3 version anyway!

With the App I created, the one thing that didn't appear to work was the updater from within SickChill. But the App was always set up to update on each restart anyway...

This new App is much cleaner than the previous versions. And by going to pip I think this will really be quite clean...

@OneCDOnly - I'll try and send through the code I am using to set these up (so far I have used this methodology for SABnzbd and SickChill)... given that the Apps I maintain for Asustor used the same methodology as the Apps I maintained for QNAP, it may be interesting to compare. FWIW, the pip method in Python3 (in my opinion) is so much nicer than having to try and export lib paths for Optware/Entware or having to cross compile for every architecture and bundle!!!

**Comment by OneCDOnly** [comment] 2020-08-21 02:50
> FWIW, the pip method in Python3 (in my opinion) is so much nicer than having to try and export lib paths for Optware/Entware or having to cross compile for every architecture and bundle!!!

Definitely! The way of the future! 😄 

I think this is how I'll rejig the QPKGs moving-forward. Just need to ensure Python3 is there (via Entware because QNAP's version is awful), then install everything via `pip`.

**Comment by miigotu** [comment] 2020-08-21 02:55
> I'll have a play and see if I can package it to install via pip (as I already do for the requirements).
> I was going to do this originally, but decided git was safer as I could test for the existence of SickChill.py.... but now I realise that this was flawed thinking... pip in python 3 will only install the python 3 version anyway!
> 
> With the App I created, the one thing that didn't appear to work was the updater from within SickChill. But the App was always set up to update on each restart anyway...
> 
> This new App is much cleaner than the previous versions. And by going to pip I think this will really be quite clean...
> 
> @OneCDOnly - I'll try and send through the code I am using to set these up (so far I have used this methodology for SABnzbd and SickChill)... given that the Apps I maintain for Asustor used the same methodology as the Apps I maintained for QNAP, it may be interesting to compare. FWIW, the pip method in Python3 (in my opinion) is so much nicer than having to try and export lib paths for Optware/Entware or having to cross compile for every architecture and bundle!!!

You also don't have to try and figure out the path to git or have an app directory set up. Just the service files to make it run automatically and any related images for their service manager UI.

Idk if asustor or qnap has a $HOME set, but default config/db path is also now $HOME/sickchill

**Comment by OneCDOnly** [comment] 2020-08-21 03:03
> Idk if asustor or qnap has a $HOME set, but default config/db path is also now $HOME/sickchill

In QNAP, everything runs as 'admin' (root user). Unfortunately, the home for admin is /root which is a tmpfs (non-persistent) and is quite small. Even have to be careful with `pip` installs as the default pip cache is in /root by default. So, after about a dozen packages are downloaded, you've got a full drive, along with a chain of errors.

That's OK, the reason QPKGs exist is to construct the environment around the needs of the app. More work for me to do. 😆

**Comment by clinton-hall** [comment] 2020-08-21 03:07
so 2 things my App does...

1. As part of post install (so only runs the once) is to make sure we have latest pip, and venv and then create the virtual environment inside of the App Directory
```
               cd $PKG_BASE_DIR
		python3 -m pip install --upgrade pip
		python3 -m pip install --user virtualenv
		python3 -m venv env
```

Then within the start.stop script for the App itself
```
DAEMON="python3 SickChill.py"
DAEMON_OPTS=" --daemon --datadir $PKG_DIR/config --pidfile $PID_FILE"
........

	cd $PKG_DIR
	#set venv
	source env/bin/activate
	python3 -m pip install sickchill #this should just skip on subsequent starts... this could be put into the post install script instead?
	python3 $DAEMON $DAEMON_OPTS
```

**Comment by clinton-hall** [comment] 2020-08-21 03:14
Yes, by default the code above will execute as `root` in Asustor... but by using the venv it isolates where the modules are installed.

What I haven't shown there, as more specific to the start-stop daemon in Asustor, is I set all to run as admin user (not root)
```
PKG_NAME="SickChill"
PKG_DIR="/usr/local/AppCentral/sickbeard-tvrage"
RUN_AS="admin:administrators"
CONFIG_DIR="$PKG_DIR/config"
PID_FILE="$PKG_DIR/$PKG_NAME.pid"
DAEMON="python3 SickChill.py"
DAEMON_OPTS=" --daemon --datadir $PKG_DIR/config --pidfile $PID_FILE"

..........
	/sbin/start-stop-daemon -S -n $PKG_NAME -p $PID_FILE -c $RUN_AS -x ${DAEMON} --${DAEMON_OPTS}
```

Note, the original package path is also `sickbeard-tvrage` because of the history of the App. If I change that, it would break the history and require everyone to install new!

**Comment by miigotu** [comment] 2020-08-21 03:50
Can we please make the app for and data for "sickchill", I have renamed every reference to sickrage/tvrage and even SickBeard is being refactored into the sickchill package. This also avoids future conflicts, because my db is going to be changing a lot soon.

**Comment by miigotu** [comment] 2020-08-21 03:51
Totally recommend everyone installing a new package. Maybe give an update to the old package that does it for them or directs them to do it. Literally every git user is going to have to do something manual to be able to use the python3 branch (by design)

**Comment by captainhowie** [comment] 2020-08-24 12:39
Sorry for the late reply to all of this.  Thanks for resolving the issue although I have no idea which branch to install (or how to change branches).
All of the apps (Nzbtomedia, sickchill and sabnzbd) have been installed via OneCD Sherpa.

Any hints welcome.
Thanks for all the work guys

**Comment by miigotu** [comment] 2020-08-24 12:42
> yeah a `#` is a "comment out character in python.... so `password = test12#34` will be handled as `test12`
> I just did a test, and if I put in quotes `password = "test12#34"` this handled the password as `test12#34`... I haven't tested as far as testing this trough the request.post (url posting)....
> 
> Also, I recommend setting up the sickchill api and using that, not the user/pass. This works better for auto-fork as well.

@captainhowie  your question was answered in the second post. Put quotes around it.

**Comment by captainhowie** [comment] 2020-08-24 12:47
> > yeah a `#` is a "comment out character in python.... so `password = test12#34` will be handled as `test12`
> > I just did a test, and if I put in quotes `password = "test12#34"` this handled the password as `test12#34`... I haven't tested as far as testing this trough the request.post (url posting)....
> > Also, I recommend setting up the sickchill api and using that, not the user/pass. This works better for auto-fork as well.
> 
> @captainhowie your question was answered in the second post. Put quotes around it.

Thanks @miigotu Perhaps I should have been clearer - the discussion has proceeded much further beyond the initial query onto the error in relation to the API link and @clinton-hall suggested I change nzbmedia to a different branch.  Thanks

**Comment by captainhowie** [comment] 2020-08-24 12:48
> I just added the params as dict to nightly.... Can't say for sure if that really did much... but between that, and having updated SickChill to latest, the auto-fork worked.
> 
> ```
> [19:28:14] [DEBUG]::SERVER: Server responded at http://10.1.1.35:8081
> [19:28:14] [INFO]::MAIN: Attempting to auto-detect tv fork
> [19:28:14] [DEBUG]::MAIN: Removing excess parameters: ['delete_files', 'delete_on', 'dir', 'dirName', 'force', 'ignore_subs', 'is priority', 'proc_dir']
> [19:28:14] [INFO]::MAIN: SickBeard:tv fork auto-detection successful ...
> [19:28:14] [INFO]::MAIN: SickBeard:tv fork set to SickChill-api
> ```
> 
> @captainhowie
> If you update SickChill and switch nzbToMedia to nightly branch, you should be able to set the apikey in autoProcessMedia.cfg and it should work correctly.

@miigotu to save you trawling through the history

**Comment by miigotu** [comment] 2020-08-24 18:42
https://github.com/clinton-hall/nzbToMedia/wiki/Branches#switching-branches-in-nzbtomedia

**Comment by miigotu** [comment] 2020-08-24 18:45
@clinton-hall I see sickchill is missing from your wiki xD

**Comment by clinton-hall** [comment] 2020-08-24 19:22
@miigotu 
To be honest, it was set to be community editable, so I'll check to be sure it wasn't added and then removed... but generally I referenced sick* forks and the people specifically added some of the various forks.

I will ensure SickChill has a dedicated section on here.

**Comment by miigotu** [comment] 2020-08-24 20:33
@clinton-hall SickChill is gonna need its own section on the wiki soon lol
https://github.com/SickChill/SickChill/compare/a353182993718fc6ee117e0edcb54e8b2cecb57d..aebe5c82ed3ced25397c702f6cc39449b549892e

**Comment by clinton-hall** [comment] 2020-08-24 22:04
I have added SickChill to the home page, and linked that directly to the nzbToMedia config details on your wiki.

I also sorted all (known) supported TV management systems in Alphabetical order (to try and avoid any issues there)... I don't expect this page to be a "sales" point. I have tried to keep neutral in most of this, and simply link to the projects that are supported.

On that. I do suspect that SickChill and a few other projects will soon become quite far removed from `SickBeard` that I will eventually need to move to separate config sections and handling.... 
I have been trying to avoid having to make users move all of their config etc (particularly where the config is actually imported in from NZBGet), so I have been trying to keep them all handled under the same SickBeard section.

Thinking about it, I could use the current auto-fork detection to write all config over to a specific SickChill (or other) section etc... But the problem I still face is with the config imported from NZBget. I could just introduce the new config details, and continue to run on the previous config until such time and new values were sent through from NZBget.... It's juts going to take some time and testing (multiple branches, some of which I don't have set up!).

**Comment by clinton-hall** [comment] 2020-08-25 00:09
@miigotu 
Sorry, I just checked your diff.... now I get it!

Yes... this would justify having your own section....

I recall when the conversation existed about adding TV series to CouchPotato.... Alas, I will be sad to stop using my CouchPotato, as I did contribute a lot of time to supporting that project.... but I will be keen to test SickChill on my movie collection 👍

**Comment by captainhowie** [comment] 2020-08-25 01:55
> https://github.com/clinton-hall/nzbToMedia/wiki/Branches#switching-branches-in-nzbtomedia

Thanks @miigotu   I get this error when trying to run the checkout nightly?

[/share/.qpkg/nzbToMedia/nzbToMedia] # git checkout nightly
error: pathspec 'nightly' did not match any file(s) known to git

**Comment by clinton-hall** [comment] 2020-08-25 02:17
@OneCDOnly
How can a user change branches for nzbToMedia  when installed from Sherpa?

**Comment by miigotu** [comment] 2020-08-25 02:24
@captainhowie I imaging first you need to `git fetch origin`

**Comment by OneCDOnly** [comment] 2020-08-25 02:56
> @OneCDOnly
> How can a user change branches for nzbToMedia when installed from Sherpa?

[This line](https://github.com/OneCDOnly/sherpa/blob/de7ccf2f7b3e8fc866d56d77fc85f3dedc05bf10/QPKGs/nzbToMedia/shared/nzbtomedia.sh#L20) would need to be changed in the service script: 
```
readonly SOURCE_GIT_BRANCH=master
```
... then the package would need to be cleaned:
```
/etc/init.d/nzbToMedia.sh clean
```

**Closed** 2020-09-06 20:07 UTC
