### ISSUE TITLE
Last update is broken without git

### ISSUE THREAD

**Issue by Koelbok** [clinton-hall/nzbToMedia#1460] opened 2018-12-27 13:46 UTC
I use a docker container with nzbget that does not have git installed. Since an automatic update everything fell apart (all postprocessing fails). This is due to cleanup.py which tries to call the git command directly and fails on errno 2 (no such file or directory, which turend out to be the git executabel that is not available). I think running without git is/should be supported?

**Comment by labrys** [comment] 2018-12-27 15:57
@Koelbok Try updating this should have been fixed in #1459.  If not could you please post the actual error message.

**Comment by labrys** [comment] 2018-12-27 16:03
I assume the issue is that in Python 2 IOError is raised on posix systems.  OSError catches WindowsError and IOError on Python 3 but fails to catch a Python 2 IOError.  If you post an error log confirming this I can have a hotfix ready in no time.

**Closed** 2018-12-27 16:17 UTC

**Comment by Koelbok** [comment] 2018-12-27 21:16
Can not update at the moment (made a hack workaround by linking /use/bin/git to /use/bin/test), but indeed, that was the error I got (will test tomorrow if it is solied in the latest greatest):

Thu Dec 27 12:54:09 2018        INFO    nzbToSickBeard:   File "/home/scripts/nzbToMedia-master/cleanup.py", line 38, 
in git_clean
Thu Dec 27 12:54:09 2018        INFO    nzbToSickBeard:     return subprocess.check_output(command)
Thu Dec 27 12:54:09 2018        INFO    nzbToSickBeard:   File "/usr/lib/python2.7/subprocess.py", line 212, in check_
output
Thu Dec 27 12:54:09 2018        INFO    nzbToSickBeard:     process = Popen(stdout=PIPE, *popenargs, **kwargs)
Thu Dec 27 12:54:09 2018        INFO    nzbToSickBeard:   File "/usr/lib/python2.7/subprocess.py", line 390, in __init
__
Thu Dec 27 12:54:09 2018        INFO    nzbToSickBeard:     errread, errwrite)
Thu Dec 27 12:54:09 2018        INFO    nzbToSickBeard:   File "/usr/lib/python2.7/subprocess.py", line 1024, in _exec
ute_child
Thu Dec 27 12:54:09 2018        INFO    nzbToSickBeard:     raise child_exception
Thu Dec 27 12:54:09 2018        INFO    nzbToSickBeard: OSError: [Errno 2] No such file or directory

**Comment by labrys** [comment] 2018-12-27 21:22
Thanks.  If it doesn't fix it I'll pop out a hot fix based on your response.  Thanks for your patience.

**Comment by Koelbok** [comment] 2018-12-28 11:52
Thanks for the fast fix. I can confirm it now works again (after removing my workaround) on version 33d95751bacfa9bf4d1106742494146b00fc74b0.

Cheers!
