### ISSUE TITLE
TorrentToMedia cleans directory after processing.

### ISSUE THREAD

**Issue by bradamon** [clinton-hall/nzbToMedia#894] opened 2015-11-29 16:41 UTC
I am using sickrage with deluge on Windows 8.1. All latest versions and python 2.7.9  32 bits. On deluge I use the execute plugin, so when a torrent is finished, it calls torrenttomedia.py. I am trying the nighty version of nzbtomedia (1cd64053b0da1d351bb6af392e1ebb904c6b6ce2).

The problem is that when a torrent finishes, the pocessing folder is deleted after the creating of symlink, so i cannot seed the file anymore. The lines "delete_on" and force_clean are deactivated. Also in sickrage i deactivated every option about deleting folder or files.
[autoprocessmedia.txt](https://github.com/clinton-hall/nzbToMedia/files/46661/autoprocessmedia.txt)

The issue can be seen in nzbtomedia.log (here is thel ogs:  
[cleandir issue.txt](https://github.com/clinton-hall/nzbToMedia/files/46662/cleandir.issue.txt)

(...)
2015-11-29 16:49:28 DEBUG   ::MAIN: Starting torrent Better.Call.Saul.S01E03.720p.HDTV.X264-DIMENSION[rarbg] in deluge
2015-11-29 16:49:33 INFO    ::CLEANDIRS: Directory F:\Torrents\complete\processed\sickrage\Better.Call.Saul.S01E03.720p.HDTV has been processed, removing ...
2015-11-29 16:49:33 INFO    ::MAIN: The C:\users\bradamon\AppData\Roaming\deluge\nzbToMedia\TorrentToMedia.py script completed successfully.

I am sure that the option "delete_on = 0" should tells the script to not delete the folder but its not working. In fact, no matter what i write after "delete_on ="  and it  keeps removing directories. 

Tell me if you need more info. Thank you very much, you are doing a fantastic job.

Regards,

Bradamon

**Comment by clinton-hall** [comment] 2015-12-05 09:18
Ok. so This script is symlinking at F:\Torrents\complete\processed\sickrage\, pointing to F:\Torrents\complete\SickRage... then SickRage moves the slymlink to the final media location...
in this case deleting the files from F:\Torrents\complete\processed\sickrage\ shouldn't cause any issues, and there shouldn't be any point to keeping these.

I do note that SickRage is trying to move then symlink back... Using this script ti do the symlink, you should just set SickRage to "move".

**Comment by bradamon** [comment] 2015-12-05 20:42
It's the opposite; the script symlinks from F:\Torrents\complete\sickrage (where deluge thinks it is located) to F:\Torrents\complete\processed\sickrage and then SickRage moves the symlink to the final location at H:\Better Call Saul\Season 01 in this case. But because the F:\Torrents\complete\processed\sickrage folder is deleted, deluge is not able to seed the file because it symlinks to an empty destination. I have changed the postprocess option to "move" in SickRage but nothing changed.
I am a bit confused, how is this supposed to work?
 sickrage folder ··········> processed folder ----------> Final Media Location? 
(·······> means symlink and ------> means to move) 
Or is the processed folder just a temporary folder which can be deleted? In that case sickrage should move the file to the final media location and after that create a symlink at the original folder. Instead of symlinking between sickrage and processed folders because they are in the same partition and i would like to keed that as clean ans possible (all physical files should be placed at final media location (other drive)) 

My english is not very well, i hope i made it clear. Thanks very much

**Comment by clinton-hall** [comment] 2015-12-05 22:58
this is how it should work.
sickrage folder ·<········· processed folder ----------> Final Media Location

so the deluge/sickrage folder should not be touched or changed in anyway. the processed folder is just a temporary location and the symlink should ultimately be moved to the final media location, but still pointing to the sickrage folder.

**Comment by clinton-hall** [comment] 2015-12-05 23:16
ok, I see where this went wrong. Now fixed in nightly branch.

If all processing stays on the same drive, I suggest using hard-link. if on different drives and no seeding required, use move. If on different drives and continued seeding is wanted, use sym. this will now be much faster, but it means if later you want to stop seeding you should consider manually moving the file to the final location (as this is currently only a symlink.)

Ultimately it would be good to move to final location, then sym-link back. but this requires 2-steps and also requires interpreting SickRage output...

**Closed** 2015-12-11 11:29 UTC
Labels: question

**Comment by bradamon** [comment] 2015-12-12 12:42
Maybe I am doing something wrong but after the fix all the files are marked as failed, because it can't find media files at symlink target folder (F:\Torrents\complete\processed\sickrage\)

[Found no media files in processed dir.txt](https://github.com/clinton-hall/nzbToMedia/files/54131/Found.no.media.files.in.processed.dir.txt)

Hardlinks works fine but now there is some problem with symlinks. Thanks in advance

**Comment by clinton-hall** [comment] 2015-12-12 20:29
Does the directory `F:\Torrents\complete\processed\sickrage\Homeland S05E10 New Normal 720P WEB-DL HEVC x265 RMTeam` exist?
Are there any files in this directory?

Or does this directory exist?
`F:\Torrents\complete\processed\sickrage\Homeland`

**Comment by bradamon** [comment] 2015-12-13 17:01
To make this more clear, if you don't mind, i made new tests with new torrents, with latest nighty version and a new log (http://pastebin.com/ECbR2fsV).
When torrent is finished at F:\Torrents\complete\sickrage, TorrentToMedia.py starts and creates a new symlinked folder in a new folder at F:\Torrents\complete\processed\sickrage\

2015-12-13 17:09:14 INFO    ::COPYLINK: SOURCE FOLDER: [F:\Torrents\complete\sickrage]
2015-12-13 17:09:14 INFO    ::COPYLINK: TARGET FOLDER: [F:\Torrents\complete\processed\sickrage\Transparent.S02E05.720p.WEBRip.x264-4yEo]
2015-12-13 17:09:14 INFO    ::COPYLINK: Sym linking SOURCE MEDIAFILE -> TARGET FOLDER

Checking this folder while the processing is running, I have realized than indeed, a new folder is created and inside that folder there is a symlinked file. Few seconds after the folder and the file inside are deleted. So answering your questions, they are temporary but there are no folders or files at processed folder. The real file is still at F:\Torrents\complete\sickrage so deluge can seed without problem. On the other hand, a new symlinked file is created at final media location (J:\Transparent\Season 02\).

So, at the end I have:

(i) A physical file at F:\Torrents\complete\sickrage (which is seeding in deluge)
(ii) No folder or files remain at F:\Torrents\complete\processed\sickrage
(iii) Symlinked file at J:\Transparent\Season 02 (linked to (i) )

But this result is exactly the reverse as what i want, which is physical files at final media location (J:/...) and a symlinked files at torrent client downloader folder (F:/...) Can this be done the way i want to?

**Comment by clinton-hall** [comment] 2015-12-13 20:22
the only way to achieve this would be to set outputDirectory to the input directory (torrent download location) then set SickRage to move and symink.

Otherwise I can revert the changes I made, and then add a script to follow multiple sum links and edit the link in torrent download folder to point directly to the source files before doing any cleanup of outputDirectory.

**Comment by bradamon** [comment] 2015-12-14 23:55
Maybe the second option is the best one, because I am not sure how to set SR to move and symlink, and also all the processed files are marked as "failed" (maybe sickrage doesnt like the symlinked files at the final media location and see them as wrong ones, idk). So, the idea of that script you say sounds really great.Thanks a lot

**Comment by clinton-hall** [comment] 2015-12-15 12:28
ok, please change
```
[Torrent]
    useLink = move-sym
```
then test this on latest nightly branch to see if this does what you want.

Basically, it will move files to outputDirectory and create a symlink at torrent download directory.
If SickRage is set to symlink, then this will move files from outputDirectory to media location and create a symlink at outputDirectory.

now, there is a check before resuming seeding, to see if the files in torrent download directory are symlinks. if they are the scriptfollows the links to the original file and points the links (in download directory) directly to the media files... THEN the outputDirectory is cleaned/deleted using the "force_clean" option.

**Comment by bradamon** [comment] 2015-12-16 23:37
I have tested the new "move-sym" option on latest nightly branch and this is what happened: The files are moved to final media location and there are two symlinks; one on torrent download directory pointing to outputdirectory, and other symlinked in this folder file pointing to file at media lcation, as you said. But as the files and folders at outputdirecory (F:\Torrents\complete\processed\sickrage) are deleted at the end, the chain of symlinks is broken and the files cannot be seed (shows an error on deluge). Right before the files is deleted i could see that it was symlinked to media location.

Torrent download directory ·······X·····> OutputDirectory ·········> Media Location.
It seems that the script is not following the links directly to the final media files.

http://pastebin.com/JG7cBV3G

**Comment by clinton-hall** [comment] 2015-12-17 11:47
it must be failing one of the tests... I'll add some more logging to help debug this. Will try and do tomorrow.

**Comment by clinton-hall** [comment] 2015-12-18 13:35
Ok... the issue is Windows doesn't play nice with sym-link tests...
I am looking at alternates.

**Comment by clinton-hall** [comment] 2015-12-18 13:41
Will need to try and use something like https://bitbucket.org/jaraco/jaraco.windows/src/default/jaraco/windows/filesystem/__init__.py?fileviewer=file-view-default

**Comment by bradamon** [comment] 2015-12-18 20:20
Thanks for the fast reply. I will try the jaraco package to make symlinks works fine on Windows. However, if this works, does anyone who wanted to symlink as I do, will need to install jaraco too?   
I was thinking about an alternate solution, maybe not the best but it could work. The thing is that if the symlinked file on OutputDirectory were keep (although the file is deleted), the chain of symlinks will remain unbroken and maybe it works. 
Torrent download directory ·······> OutputDirectory ·······> Media Location.
The downside of this is that there would be two copies of symlinked files; on torrent download directory and on OutputDirectory, but anyway this wouldnt be a real problem.

**Comment by clinton-hall** [comment] 2015-12-19 00:54
no... I am adding jaraco packageto my repo... no need to install other, since it still requires me editing the main repo to work with it.

I just need to run some tests here before I push the changes.

**Comment by clinton-hall** [comment] 2015-12-19 01:05
update to latest nightly and test again...
It is difficult for me to actually test the entire windows flow, but in theory this should now follow the sym-links and directly link to end point.

**Comment by clinton-hall** [comment] 2015-12-19 01:12
in theory, I can use jaraco to simplify my code a lot. this repo already does a lot that I have "reproduced" in my repo... and jaraco is a lot cleaner than my methods...

**Comment by bradamon** [comment] 2015-12-19 12:37
Wow! that's amazing! I'm going to upgrade to the latest nightly branch and see how it's going. I will post the resusts as soon as i get them.

**Comment by bradamon** [comment] 2015-12-20 17:46
I found problems with the new nighty branch and SickRage. When TorrentToMedia calls sickrage postprocess, it turns back an error and ends stuck (i have to manually restart sickrage to make it run again): http://pastebin.com/Rc6KmrXQ
Symlinked file is created at torrent downloaded directory, linked to a file at OutpurDirectory, instead of linked to end point at final media location (due to an error you can see at log above)

However, it works perfectly with CouchPotato, and the chain of links are as expected. Deluge now can seed the symlinked files linked to final media location: http://pastebin.com/U1yCnnCi
(the only thing it didnt do is to resume the CP torrent after processing).

Thanks very much,

**Comment by clinton-hall** [comment] 2015-12-21 11:06
For SickRage, it looks like there must have been an update that changed this process... Hoping this gets fixed, or someone tells me what needs to change.

For CouchPotato, dos the logs end there?
It looks like there was an error that stopped the script before it could resume the torrent... But indeed it seems to error before it fixed the Sym-links and before it cleans the output directory.

**Comment by clinton-hall** [comment] 2015-12-21 11:16
Can you run manually from command line?

`C:\Python27\python.exe 'C:\users\bradamon\AppData\Roaming\\deluge\nzbToMedia\TorrentToMedia.py' '607d0f69d032207d5cc11e269992ff0fd82182f1' 'The Shawshank Redemption 1994 720p Bluray DTS SilverTorrentHD' 'F:\\Torrents\\complete\\couchpotato'`

The post the output from the command line. this should capture any errors.

**Comment by bradamon** [comment] 2015-12-21 23:08
Yes, the logs regarding couchpotato ended there. I executed that command from cli but it didn't return anything. A window opens and immediately closes.

**Comment by clinton-hall** [comment] 2015-12-22 11:21
ok... hopefully I can find some time to set up some tests for this to see what is going on.

**Comment by bradamon** [comment] 2015-12-24 17:59
Maybe its just something wrong about my sickrage, maybe others don't have this problem and SR doesn't crash (web browser returns a "ERR_TOO_MANY_REDIRECTS" message). 

Here is the (part of the) log from sickrage.log:

2015-12-24 17:16:08 INFO::TORNADO::Processing completed
2015-12-24 17:17:28 DEBUG::TORNADO::Failed doing webui request [/home/getManualSearchStatus?show=279121]: Traceback (most recent call last):
  File "C:\SickRage-master-2\sickbeard\webserve.py", line 209, in prepare
    result = yield Task(self.async_call, method, threading.currentThread().name)
  File "C:\SickRage-master-2\lib\tornado\gen.py", line 870, in run
    value = future.result()
  File "C:\SickRage-master-2\lib\tornado\concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "C:\SickRage-master-2\lib\tornado\gen.py", line 505, in Task
    func(*args, callback=_argument_adapter(set_result), **kwargs)
  File "C:\SickRage-master-2\lib\tornado\concurrent.py", line 371, in wrapper
    future = getattr(self, executor).submit(fn, self, *args, **kwargs)
  File "C:\SickRage-master-2\lib\concurrent\futures\thread.py", line 111, in submit
    self._adjust_thread_count()
  File "C:\SickRage-master-2\lib\concurrent\futures\thread.py", line 127, in _adjust_thread_count
    t.start()
  File "C:\Python27\lib\threading.py", line 745, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread

Perhaps I have to open a ticket at SR forum but maybe this log helps you on debugging if the error is due to torrenttomedia.py.

**Comment by clinton-hall** [comment] 2015-12-26 08:28
I have seen this error a while back. I believe it was due to issues with DNS not being properly resolved...

**Comment by bradamon** [comment] 2015-12-28 20:23
could it be any optioin to use different automatic processing methods depending on app used (SR, Couchpotato, Mylar, etc)? Maybe the sickrage problem doesn't have an early solution, so it could be great to keep using the new "move-sym" method on others (like couchpotato) which don't have this DNS issue.

**Comment by clinton-hall** [comment] 2015-12-28 20:37
it is the move-sym that hasn't been tested yet... I don't see how this DNS issue is related to these changes...

**Comment by bradamon** [comment] 2015-12-31 15:57
You are right, my sickrage webui problem has nothing to do with NzbtoMedia scripts. It was just a coincidence in time between my testing of move-sym from latest nighty branches and the SR problem. 
But there is no relation between them. What do you mean when you say that the move-sym hasn't been tested yet? 2 weeks ago I started to test this new option and -with the exception of sickrage- it was working fine on couchpotato; move-sym resolves my first symlinks problems. I have opened a ticket on sickrage to fix it's issue. I guess that once that is solved, the "move-sym" will also work fine on SR.

**Comment by clinton-hall** [comment] 2016-01-01 10:04
I didn't think this had been verified yet. The CouchPotato processing showed that the script failed before resuming torrent seeding, so there is an issue somewhere.
