### ISSUE TITLE
RADARR: Server returned status 405

### ISSUE THREAD

**Issue by mbeebe43083** [clinton-hall/nzbToMedia#1831] opened 2021-06-03 13:30 UTC
Radarr nightly has been updated to 4.0. This removes the legacy mono API and x86 support. This seems to cause failure with a 405 error during post processing. 

**Technical Specs**
1. Windows 10 x64 10.0.19042.985
2. Python version 3.9.5
3. NZBGet 21.1-testing-r2329
4. Radarr 4.0.0.5079 nightly

**Expected behavior**
Script will likely need to updated for future radarr support. I imagine this will be the same for sonarr as well.

**Log**
2021-05-31 17:32:26 DEBUG   ::RADARR: Opening URL: http://localhost:7878/api/command with PARAMS: {'name': 'DownloadedMoviesScan', 'path': 'D:\\Complete\\Movies\\***', 'downloadClientId': '***', 'importMode': 'Copy'}
2021-05-31 17:32:26 POSTPROCESS::RADARR: Starting DownloadedMoviesScan scan for ***
2021-05-31 17:32:26 ERROR   ::RADARR: Server returned status 405

**Comment by clinton-hall** [comment] 2021-06-04 10:30
try updating to the Radarr-apiv3 branch to see if this works.

**Comment by BradKollmyer** [comment] 2021-06-05 22:50
That change fixed the issue.

**Comment by clinton-hall** [comment] 2021-06-07 03:46
thanks. Merged into nightly branch

**Comment by buzzke** [comment] 2021-06-07 06:44
Hey
That did not work for me.

**Running Radarr**
Version 4.0.0.5079
Package Version 4.0.0.5079-ls94 by linuxserver.io

**Git branch**
  Radarr-apiv3
  master
* nightly

I still have post-process errors after succesful pull of nightly (and changing it in autoprocesMedia.cfg)
Here is the log

`2021-06-07 06:34:33 INFO    ::MAIN: #########################################################
2021-06-07 06:34:33 INFO    ::MAIN: ## ..::[nzbToMedia.py]::.. ##
2021-06-07 06:34:33 INFO    ::MAIN: #########################################################
2021-06-07 06:34:33 DEBUG   ::MAIN: Options passed into nzbToMedia: ['/downloads/scripts/nzbToMedia/nzbToRadarr.py']
2021-06-07 06:34:33 INFO    ::MAIN: Script triggered from NZBGet Version 21.1-testing-r2329 ((HEAD detached at v21.1-r2329)).
2021-06-07 06:34:33 DEBUG   ::MAIN: Adding NZB download info for directory /downloads/completed/movie/The.Conjuring.the.Devil.Made.Me.Do.It.2021.1080p.HMAX.WEB-DL.DDP5.1.Atmos.x264-CMRG to database
2021-06-07 06:34:33 DB      ::MAIN: nzbtomedia.db: UPDATE downloads SET input_name = ?, input_hash = ?, input_id = ?, client_agent = ?, status = ?, last_update = ? WHERE input_directory = ? with args ['The.Conjuring.the.Devil.Made.Me.Do.It.2021.1080p.HMAX.WEB-DL.DDP5.1.Atmos.x264-CMRG', 'cd503933a552472a89c0900737edf2cf', 'cd503933a552472a89c0900737edf2cf', 'nzbget', 0, 737948, '/downloads/completed/movie/The.Conjuring.the.Devil.Made.Me.Do.It.2021.1080p.HMAX.WEB-DL.DDP5.1.Atmos.x264-CMRG']
2021-06-07 06:34:33 DB      ::MAIN: nzbtomedia.db: INSERT OR IGNORE INTO downloads (input_name, input_hash, input_id, client_agent, status, last_update) VALUES (?, ?, ?, ?, ?, ?) with args ['The.Conjuring.the.Devil.Made.Me.Do.It.2021.1080p.HMAX.WEB-DL.DDP5.1.Atmos.x264-CMRG', 'cd503933a552472a89c0900737edf2cf', 'cd503933a552472a89c0900737edf2cf', 'nzbget', 0, 737948]
2021-06-07 06:34:34 INFO    ::MAIN: Auto-detected SECTION:Radarr
2021-06-07 06:34:34 DEBUG   ::MAIN: Checking for archives to extract in directory: /downloads/completed/movie/The.Conjuring.the.Devil.Made.Me.Do.It.2021.1080p.HMAX.WEB-DL.DDP5.1.Atmos.x264-CMRG
2021-06-07 06:34:34 INFO    ::MAIN: Calling Radarr:movie to post-process:The.Conjuring.the.Devil.Made.Me.Do.It.2021.1080p.HMAX.WEB-DL.DDP5.1.Atmos.x264-CMRG
2021-06-07 06:34:34 INFO    ::MAIN: Attemping imdbID lookup for The.Conjuring.the.Devil.Made.Me.Do.It.2021.1080p.HMAX.WEB-DL.DDP5.1.Atmos.x264-CMRG
2021-06-07 06:34:34 INFO    ::MAIN: Searching folder and file names for imdbID ...
2021-06-07 06:34:34 INFO    ::MAIN: Searching IMDB for imdbID ...
2021-06-07 06:34:35 DEBUG   ::MAIN: Opening URL: http://www.omdbapi.com
2021-06-07 06:34:35 INFO    ::MAIN: Found imdbID [tt7069210]
2021-06-07 06:34:35 DEBUG   ::SERVER: Attempting to connect to server at http://192.168.1.5:7878/api/v3/command
2021-06-07 06:34:35 DEBUG   ::SERVER: Server responded at http://192.168.1.5:7878/api/v3/command
2021-06-07 06:34:35 DEBUG   ::EXCEPTION: Replacing file name EHXVbRoOTscG0S4jFZ1g with directory name The.Conjuring.the.Devil.Made.Me.Do.It.2021.1080p.HMAX.WEB-DL.DDP5.1.Atmos.x264-CMRG
2021-06-07 06:34:35 DEBUG   ::EXCEPTION: Replacing file name /downloads/completed/movie/The.Conjuring.the.Devil.Made.Me.Do.It.2021.1080p.HMAX.WEB-DL.DDP5.1.Atmos.x264-CMRG/EHXVbRoOTscG0S4jFZ1g.mkv with download name /downloads/completed/movie/The.Conjuring.the.Devil.Made.Me.Do.It.2021.1080p.HMAX.WEB-DL.DDP5.1.Atmos.x264-CMRG/The.Conjuring.the.Devil.Made.Me.Do.It.2021.1080p.HMAX.WEB-DL.DDP5.1.Atmos.x264-CMRG.mkv
2021-06-07 06:34:35 DEBUG   ::MAIN: Renaming: /downloads/completed/movie/The.Conjuring.the.Devil.Made.Me.Do.It.2021.1080p.HMAX.WEB-DL.DDP5.1.Atmos.x264-CMRG/The.Conjuring.the.Devil.Made.Me.Do.It.2021.1080p.HMAX.WEB-DL.DDP5.1.Atmos.x264-CMRG.mkv to: /downloads/completed/movie/The.Conjuring.the.Devil.Made.Me.Do.It.2021.1080p.HMAX.WEB-DL.DDP5.1.Atmos.x264-CMRG/The.Conjuring.the.Devil.Made.Me.Do.It.2021.1080p.HMAX.WEB-DL.DDP5.1.Atmos.x264-CMRG.cp(tt7069210).mkv
2021-06-07 06:34:35 DEBUG   ::RADARR: Opening URL: http://192.168.1.5:7878/api/v3/command with PARAMS: {'name': 'DownloadedMoviesScan', 'path': '/downloads/completed/movie/The.Conjuring.the.Devil.Made.Me.Do.It.2021.1080p.HMAX.WEB-DL.DDP5.1.Atmos.x264-CMRG', 'downloadClientId': 'cd503933a552472a89c0900737edf2cf', 'importMode': 'Move'}
2021-06-07 06:34:35 POSTPROCESS::RADARR: Starting DownloadedMoviesScan scan for The.Conjuring.the.Devil.Made.Me.Do.It.2021.1080p.HMAX.WEB-DL.DDP5.1.Atmos.x264-CMRG`

**Comment by clinton-hall** [comment] 2021-06-07 08:04
Did Radarr do the download scan?
What do Radarr logs show from 06:34:35?

I think the issue is the new api doesn't send back the same response, so we can't check to see when the process completes.

**Comment by buzzke** [comment] 2021-06-07 08:49
Hey.  Yes Radarr did the download scan.  The movie was moved correctly to the destination.
But because the script thinks the download failed, it triggers Radarr into thinking the download failed.  And then downloads another version of the movie ...
So in short:
- Post process script mentions that download failed
- But in reality Radarr did the download scan, and moved the movie to its destination

**Comment by clinton-hall** [comment] 2021-06-07 09:52
I just removed that logging (we don't need the "state" to be returned.
See if that (in latest nightly) works any better.

**Comment by buzzke** [comment] 2021-06-07 11:36
Thx
That fixed it indeed

2021-06-07 11:33:36 POSTPROCESS::RADARR: Starting DownloadedMoviesScan scan for Occupation.Rainfall.2020.1080p.WEB-DL.DD5.1.H.264-FGT
2021-06-07 11:33:37 DEBUG   ::RADARR: Scan started with id: 107437
2021-06-07 11:33:37 POSTPROCESS::RADARR: Checking for status change, please stand by ...
2021-06-07 11:33:37 ERROR   ::RADARR: Radarr did not return expected json data.
2021-06-07 11:34:27 POSTPROCESS::RADARR: Checking for status change, please stand by ...
2021-06-07 11:34:27 ERROR   ::RADARR: Radarr did not return expected json data.
2021-06-07 11:35:17 POSTPROCESS::RADARR: Checking for status change, please stand by ...
2021-06-07 11:35:18 ERROR   ::RADARR: Radarr did not return expected json data.
2021-06-07 11:36:08 POSTPROCESS::RADARR: Checking for status change, please stand by ...
2021-06-07 11:36:08 ERROR   ::RADARR: Radarr did not return expected json data.
2021-06-07 11:36:08 POSTPROCESS::RADARR: SUCCESS: Input Directory [/downloads/completed/movie/Occupation.Rainfall.2020.1080p.WEB-DL.DD5.1.H.264-FGT] has been processed and removed
2021-06-07 11:36:08 DB      ::DB: Updating DB download status of Occupation.Rainfall.2020.1080p.WEB-DL.DD5.1.H.264-FGT to 1
2021-06-07 11:36:08 DB      ::MAIN: nzbtomedia.db: UPDATE downloads SET status=?, last_update=? WHERE input_name=? with args [1, 737948, 'Occupation.Rainfall.2020.1080p.WEB-DL.DD5.1.H.264-FGT']
2021-06-07 11:36:09 INFO    ::MAIN: The /downloads/scripts/nzbToMedia/nzbToRadarr.py script completed successfully.

**Comment by clinton-hall** [comment] 2021-06-08 01:14
oh.... interesting. `Scan started with id: 107437`
So we do get the process id (in a different format).
Now I need to figure out what the format is of the api to get the status of the process...

**Comment by clinton-hall** [comment] 2021-06-08 01:31
Actually, that api looks fine too... once again, there is no "state" returned. And the script relies on this to know when completed.

So I need to figure out what the format is of the command api, but this is not shown in the radarr api docs.
https://radarr.video/docs/api/#/

**Comment by clinton-hall** [comment] 2021-06-08 03:15
Can you switch to `Radarr_apiv3` to test this?
Looking at the Radarr source it looks like they changed `state` to `status` in which case this should be an easy enough fix.

**Comment by buzzke** [comment] 2021-06-08 11:13
Switched to branch Radarr_apiv3 version
Commit done on common.py with change on line 48 from State to Status.
But i then receive again error 405 in the log
So reverted it back.


2021-06-08 11:09:42 INFO    ::MAIN: #########################################################
2021-06-08 11:09:42 INFO    ::MAIN: ## ..::[nzbToMedia.py]::.. ##
2021-06-08 11:09:42 INFO    ::MAIN: #########################################################
2021-06-08 11:09:42 DEBUG   ::MAIN: Options passed into nzbToMedia: ['/downloads/scripts/nzbToMedia/nzbToRadarr.py']
2021-06-08 11:09:42 INFO    ::MAIN: Script triggered from NZBGet Version 21.1-testing-r2329 ((HEAD detached at v21.1-r2329)).
2021-06-08 11:09:42 DEBUG   ::MAIN: Adding NZB download info for directory /downloads/completed/movie/No.Mans.Land.2021.1080p.WEB-DL.DD5.1.H.264-EVO to database
2021-06-08 11:09:42 DB      ::MAIN: nzbtomedia.db: UPDATE downloads SET input_name = ?, input_hash = ?, input_id = ?, client_agent = ?, status = ?, last_update = ? WHERE input_irectory = ? with args ['No.Mans.Land.2021.1080p.WEB-DL.DD5.1.H.264-EVO', 'e65e2ddb4898432d9f9acb3007abb64a', 'e65e2ddb4898432d9f9acb3007abb64a', 'nzbget', 0, 737949, '/downloas/completed/movie/No.Mans.Land.2021.1080p.WEB-DL.DD5.1.H.264-EVO']
2021-06-08 11:09:42 DB      ::MAIN: nzbtomedia.db: INSERT OR IGNORE INTO downloads (input_name, input_hash, input_id, client_agent, status, last_update) VALUES (?, ?, ?, ?, ?, ) with args ['No.Mans.Land.2021.1080p.WEB-DL.DD5.1.H.264-EVO', 'e65e2ddb4898432d9f9acb3007abb64a', 'e65e2ddb4898432d9f9acb3007abb64a', 'nzbget', 0, 737949]
2021-06-08 11:09:43 INFO    ::MAIN: Auto-detected SECTION:Radarr
2021-06-08 11:09:43 DEBUG   ::MAIN: Checking for archives to extract in directory: /downloads/completed/movie/No.Mans.Land.2021.1080p.WEB-DL.DD5.1.H.264-EVO
2021-06-08 11:09:43 INFO    ::MAIN: Calling Radarr:movie to post-process:No.Mans.Land.2021.1080p.WEB-DL.DD5.1.H.264-EVO
2021-06-08 11:09:43 INFO    ::MAIN: Attemping imdbID lookup for No.Mans.Land.2021.1080p.WEB-DL.DD5.1.H.264-EVO
2021-06-08 11:09:43 INFO    ::MAIN: Searching folder and file names for imdbID ...
2021-06-08 11:09:43 INFO    ::MAIN: Searching IMDB for imdbID ...
2021-06-08 11:09:44 DEBUG   ::MAIN: Opening URL: http://www.omdbapi.com
2021-06-08 11:09:44 ERROR   ::MAIN: No imdbID returned from omdbapi.com
2021-06-08 11:09:44 WARNING ::MAIN: Unable to find a imdbID for No.Mans.Land.2021.1080p.WEB-DL.DD5.1.H.264-EVO
2021-06-08 11:09:44 DEBUG   ::SERVER: Attempting to connect to server at http://192.168.1.5:7878/api/command
2021-06-08 11:09:44 DEBUG   ::SERVER: Server responded at http://192.168.1.5:7878/api/command
2021-06-08 11:09:44 DEBUG   ::EXCEPTION: Replacing file name XbEUXZ0rcdn4bttFeYX with directory name No.Mans.Land.2021.1080p.WEB-DL.DD5.1.H.264-EVO
2021-06-08 11:09:44 DEBUG   ::EXCEPTION: Replacing file name /downloads/completed/movie/No.Mans.Land.2021.1080p.WEB-DL.DD5.1.H.264-EVO/XbEUXZ0rcdn4bttFeYX.mkv with download nam /downloads/completed/movie/No.Mans.Land.2021.1080p.WEB-DL.DD5.1.H.264-EVO/No.Mans.Land.2021.1080p.WEB-DL.DD5.1.H.264-EVO.mkv
2021-06-08 11:09:45 DEBUG   ::RADARR: Opening URL: http://192.168.1.5:7878/api/command with PARAMS: {'name': 'DownloadedMoviesScan', 'path': '/downloads/completed/movie/No.MansLand.2021.1080p.WEB-DL.DD5.1.H.264-EVO', 'downloadClientId': 'e65e2ddb4898432d9f9acb3007abb64a', 'importMode': 'Move'}
2021-06-08 11:09:45 POSTPROCESS::RADARR: Starting DownloadedMoviesScan scan for No.Mans.Land.2021.1080p.WEB-DL.DD5.1.H.264-EVO
2021-06-08 11:09:45 ERROR   ::**RADARR: Server returned status 405**
2021-06-08 11:09:45 ERROR   ::MAIN: A problem was reported in the /downloads/scripts/nzbToMedia/nzbToRadarr.py script.

**Comment by clinton-hall** [comment] 2021-06-08 19:29
Thanks for confirming. I have now merged back into nightly.

What I don't know is if this is backwards compatible with Radarr master. (I believe Master does support api v3, so hopefully it is).
I'll leave in nightly to see if there are any reports of issues before merging up to master.

**Comment by buzzke** [comment] 2021-06-11 08:15
Sure.
Thx for the feedback!
Glad to help!

**Closed** 2024-04-26 01:31 UTC
