### ISSUE TITLE
Latest commits break the update process.

### ISSUE THREAD

**Issue by Trotter73** [clinton-hall/nzbToMedia#1527] opened 2019-01-16 09:00 UTC
Hi,

Windows 10, Python 2.7.15, Sab 2.3.6, Medusa..

The latest commits look like they have broken the update process again on Windows, this is also preventing nzbToMedia from running.

Sab is showing the error:- Exception: ('Required subfolders missing:', ['utils'])

```
Changing to directory: C:\Utils\nzbToMedia

-- Cleaning bytecode --
Error: [Error 2] The system cannot find the file specified

Directory is not a git repository

Force cleaning folder: libs
Skipping required subfolders ['common', 'custom', 'py2', 'win']

Force cleaning folder: core
Skipping required subfolders ['auto_process', 'extractor', 'utils']
Traceback (most recent call last):
File "C:\Utils\nzbToMedia\nzbToSickBeard.py", line 261, in <module>
import nzbToMedia
File "C:\Utils\nzbToMedia\nzbToMedia.py", line 627, in <module>
cleanup.clean(cleanup.FOLDER_STRUCTURE)
File "C:\Utils\nzbToMedia\cleanup.py", line 170, in clean
force_clean_folder(folder, subfolders)
File "C:\Utils\nzbToMedia\cleanup.py", line 136, in force_clean_folder
raise Exception('Required subfolders missing:', missing)
Exception: ('Required subfolders missing:', ['utils'])
```
EDIT:-

A  manual update is required to get things working again, feel free to close if it's not worth looking at :)

EDIT 2:-

It looks like there is still an issue with the clean up process, I get the following from Sab and if I run manually..
```
WARNING: Automatic cleanup could not be executed.
         If errors occur, manual cleanup may be required.
REASON : Error: [Error 2] The system cannot find the file specified
```

**Comment by Trotter73** [comment] 2019-01-16 20:43
Hi,

I download the zip and extract, I dont have GIT on my windows machine, if I get a chance I may give it a go see if it makes a difference, I think I saw a "Portable" version.. Would there be much of a difference between the two ?

**Comment by labrys** [comment] 2019-01-16 20:44
I have an idea as to why this occurs and if I'm not mistaken only affects non-git installs.  Unfortunately this refactor merged from nightly before it had been thoroughly tested.   I will attempt to reproduce it so I can put out a hot fix.

**Comment by labrys** [comment] 2019-01-16 20:48
@clinton-hall I would really like to implement automated testing using Travis and other continuous integration tools to avoid these kinds of issues in the future.

**Comment by clinton-hall** [comment] 2019-01-16 20:59
@labrys 
I agree that this appears to affect the non-git installs. I think it occurs at the changes between 12.0.5-RC.1 and 12.0.6... However I can't reproduce without killing my git.

Happy to implement automated testing. I don't have enough knowledge on these systems, but more than happy for you to put something in.

Like everything is this project, I test what I can, but it is hard to test every setup (i.e. I can't test OSX, I can't (currently) test the dockers or the unraid systems etc). I tried many tests of the updater (using git) and was confident that this was working and upgrade errors weren't present....

**Comment by Trotter73** [comment] 2019-01-16 21:15
Thanks for looking into this guys, if you need me to take anything out for spin drop me a line.

**Comment by labrys** [comment] 2019-01-16 22:55
@clinton-hall The most likely reason it broke during the most recent push is the cleanup script for non-git installs is fairly primitive.  

It only removes redundant folders and complains if expected folders are not found.
The git clean process is much more reliable.

**Comment by Trotter73** [comment] 2019-01-17 15:22
Hi,

Something occurred to me earlier.. Yes I am installing from a zip rather than GIT, however on the first run of the script, it checks for an update, can’t determine a version so updates anyway (successfully), would I be correct in saying at that point I effectively have a GIT install ? Looking in my nzbtomedia folder I see the usual git “.xxxx “ files.. Just a though…

**Comment by labrys** [comment] 2019-01-17 22:10
@Trotter73 Unless there is a `.git` folder in the `nzbToMedia` folder you are not using a git-installed version of `nzbToMedia` and it does not update a source install to a git install either.  Files like `.gitignore` will be present on both git and source installs.

**Comment by Trotter73** [comment] 2019-01-18 10:48
Gotcha, thanks for the clarification !!

**Closed** 2019-08-09 09:44 UTC
